### ISSUE TITLE
Looks more brainf**ked than brainf**k

### ISSUE THREAD

**Issue by louy2** [mattn/ws#1]
A language based on whitespaces? I'm shocked.

**Comment by mattn** [comment]
what?

**Comment by louy2** [comment]
I saw a parser that parses whitespace patterns into stack-based operations, so I assume this is a programming language based on whitespaces. I am surprised at this brilliant idea. No sarcasm involved.

[Brainf**k](https://en.wikipedia.org/wiki/Brainfuck) is a language based solely on symbols.

**Comment by mattn** [comment]
@louy2 if you have interesting vm of brainf**k, see https://github.com/mattn/bf

**Comment by mattn** [comment]
as you said, bf is language based.
